INSERT INTO media_files (file_name, mime_type, size_bytes, storage_path, alt_text)
VALUES
    ('service-drilling-rig.jpg', 'image/jpeg', 245120, 'seed/media/service-drilling-rig.jpg', 'Drilling rig at field site'),
    ('service-topography-drone.jpg', 'image/jpeg', 198450, 'seed/media/service-topography-drone.jpg', 'Drone topographic survey'),
    ('service-lab-testing.jpg', 'image/jpeg', 176800, 'seed/media/service-lab-testing.jpg', 'Laboratory material testing'),
    ('project-highway.jpg', 'image/jpeg', 268700, 'seed/media/project-highway.jpg', 'Highway investigation project'),
    ('project-factory.jpg', 'image/jpeg', 251900, 'seed/media/project-factory.jpg', 'Factory foundation survey'),
    ('project-housing.jpg', 'image/jpeg', 223560, 'seed/media/project-housing.jpg', 'Housing development site'),
    ('equipment-drill-01.jpg', 'image/jpeg', 164300, 'seed/media/equipment-drill-01.jpg', 'Core drilling machine'),
    ('equipment-cpt-01.jpg', 'image/jpeg', 158420, 'seed/media/equipment-cpt-01.jpg', 'Cone penetration testing equipment'),
    ('equipment-gps-01.jpg', 'image/jpeg', 142250, 'seed/media/equipment-gps-01.jpg', 'GPS rover equipment'),
    ('equipment-lab-01.jpg', 'image/jpeg', 151880, 'seed/media/equipment-lab-01.jpg', 'Laboratory testing set');

INSERT INTO pages (title, slug, summary, content, status, published_at)
VALUES
    ('Gioi thieu cong ty', 'gioi-thieu-cong-ty', 'Trang gioi thieu tong quan ve Hanoi Survey.', '<p>Hanoi Survey cung cap dich vu khao sat, thi nghiem va quan trac cho cac du an dan dung, cong nghiep va ha tang.</p><p>Du lieu nay duoc tao de kiem tra giao dien va API.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 120 DAY)),
    ('Nang luc nhan su', 'nang-luc-nhan-su', 'Thong tin ve doi ngu ky su va chuyen gia.', '<p>Doi ngu gom cac ky su dia chat, dia hinh, thuy van va thi nghiem hien truong.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 110 DAY)),
    ('Nang luc thiet bi', 'nang-luc-thiet-bi', 'Tong hop thiet bi khoan, do dac va thi nghiem.', '<p>He thong thiet bi duoc dau tu dong bo phuc vu nhieu loai hinh du an.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 105 DAY)),
    ('Quy trinh trien khai du an', 'quy-trinh-trien-khai-du-an', 'Mo ta cac buoc trien khai khao sat ngoai nghiem thu.', '<p>Quy trinh bao gom tiep nhan yeu cau, khao sat hien truong, lap bao cao va ban giao ho so.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 95 DAY)),
    ('Cam ket an toan lao dong', 'cam-ket-an-toan-lao-dong', 'Chinh sach an toan khi thi cong va khao sat.', '<p>An toan lao dong va kiem soat rui ro la yeu to bat buoc trong moi cong trinh.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 80 DAY)),
    ('Chinh sach bao mat', 'chinh-sach-bao-mat', 'Noi dung chinh sach bao mat thong tin khach hang.', '<p>Thong tin lien he va du lieu khach hang duoc luu tru va xu ly theo quy dinh noi bo.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 60 DAY)),
    ('Dieu khoan su dung', 'dieu-khoan-su-dung', 'Dieu khoan su dung website va dich vu.', '<p>Trang du lieu mau phuc vu kiem tra kha nang hien thi noi dung dai.</p>', 'DRAFT', NULL),
    ('Tuyen dung ky su hien truong', 'tuyen-dung-ky-su-hien-truong', 'Thong tin tuyen dung noi bo.', '<p>Can bo sung nhan su cho cac du an khao sat dia chat va dia hinh tai mien Bac.</p>', 'DRAFT', NULL);

INSERT INTO posts (category_id, title, slug, excerpt, content, status, published_at)
VALUES
    ((SELECT id FROM post_categories WHERE slug = 'tin-tuc'), 'Khoi cong goi khao sat cao toc phia Bac', 'khoi-cong-goi-khao-sat-cao-toc-phia-bac', 'Du an khao sat phuc vu lap bao cao tien kha thi cho tuyen cao toc moi.', '<p>Doan tu van da huy dong may khoan, thiet bi do dac va nhan su de trien khai trong 45 ngay.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 40 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'tin-tuc'), 'Hoan thanh khao sat nha may tai Hung Yen', 'hoan-thanh-khao-sat-nha-may-tai-hung-yen', 'Hoan thanh khoi luong khoan va thi nghiem hien truong cho khu cong nghiep moi.', '<p>Ket qua so bo cho thay dia tang phu hop voi phuong an mong coc du kien.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 36 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'tin-tuc'), 'Ban giao ho so du an khu do thi ven song', 'ban-giao-ho-so-du-an-khu-do-thi-ven-song', 'Ho so bao gom bao cao dia chat, dia hinh va de xuat giai phap nen mong.', '<p>Chu dau tu danh gia cao toc do trien khai va chat luong tai lieu.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 31 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'tin-tuc'), 'Mo rong phong thi nghiem vat lieu', 'mo-rong-phong-thi-nghiem-vat-lieu', 'Bo sung thiet bi phuc vu cac chi tieu nen, be tong va cat da.', '<p>Phong thi nghiem moi giup tang cong suat va rut ngan tien do tra ket qua.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 27 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'tin-tuc'), 'Khai truong van phong du an tai Quang Ninh', 'khai-truong-van-phong-du-an-tai-quang-ninh', 'Van phong ho tro trien khai cac du an ha tang va cong nghiep khu vuc Dong Bac.', '<p>Don vi bo tri nhan su ky thuat va dieu phoi truc tiep tai cong truong.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 21 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'tin-tuc'), 'Cap nhat danh muc thiet bi quy 2', 'cap-nhat-danh-muc-thiet-bi-quy-2', 'Them nhieu thiet bi khoan va do dac phuc vu du an lon.', '<p>Danh muc cap nhat giup doi thi cong dap ung dong thoi nhieu goi thau.</p>', 'DRAFT', NULL),
    ((SELECT id FROM post_categories WHERE slug = 'kien-thuc'), 'Cach doc bao cao khao sat dia chat cong trinh', 'cach-doc-bao-cao-khao-sat-dia-chat-cong-trinh', 'Tong hop nhung muc quan trong trong bao cao dia chat.', '<p>Can chu y mat cat dia tang, muc nuoc ngam, chi tieu co ly va khuyen nghi nen mong.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 18 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'kien-thuc'), 'Phan biet khao sat dia hinh va do dac hoan cong', 'phan-biet-khao-sat-dia-hinh-va-do-dac-hoan-cong', 'Hai hang muc co muc tieu va san pham ban giao khac nhau.', '<p>Khao sat dia hinh phuc vu thiet ke, con hoan cong phuc vu nghiem thu hien trang sau thi cong.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 15 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'kien-thuc'), 'Khi nao can thi nghiem CPTu', 'khi-nao-can-thi-nghiem-cptu', 'CPTu phu hop voi nen dat yeu va can xac dinh suc khang mui lien tuc.', '<p>Phuong phap nay thu duoc du lieu nhanh va giam so luong mau xao tron.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 12 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'kien-thuc'), 'Quan trac lun cong trinh gom nhung gi', 'quan-trac-lun-cong-trinh-gom-nhung-gi', 'Tong hop cac hang muc quan trac lun, nghieng, dich chuyen ngang.', '<p>Can lap ke hoach tan suat do, moc quan trac va nguong canh bao ngay tu dau du an.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 9 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'kien-thuc'), 'Lua chon phuong an khoan lay mau cho nen dat phuc tap', 'lua-chon-phuong-an-khoan-lay-mau-cho-nen-dat-phuc-tap', 'De xuat theo tung dieu kien dia tang va muc nuoc ngam.', '<p>Can can nhac mau nguyen dang, chieu sau khoan va dieu kien tiep can hien truong.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY)),
    ((SELECT id FROM post_categories WHERE slug = 'kien-thuc'), 'Checklist nghiem thu cong tac khao sat', 'checklist-nghiem-thu-cong-tac-khao-sat', 'Danh sach tai lieu va buoc kiem tra khi nghiem thu.', '<p>Day la bai viet nhap de kiem tra trang thai ban nhap.</p>', 'DRAFT', NULL);

INSERT INTO services (category_id, title, slug, overview, content, icon, cover_image_path, status, published_at)
VALUES
    ((SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Khao sat dia chat cho nha cao tang', 'khao-sat-dia-chat-cho-nha-cao-tang', 'Khoan, lay mau va thi nghiem phuc vu thiet ke mong nha cao tang.', '<p>Goi dich vu bao gom khoan xoay rua, SPT, mau nguyen dang, lap bao cao dia chat va khuyen nghi giai phap mong.</p>', 'drill', 'seed/media/service-drilling-rig.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 70 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Khao sat dia chat cho nha xuong cong nghiep', 'khao-sat-dia-chat-cho-nha-xuong-cong-nghiep', 'Danh gia nen dat cho nha may, kho va cong trinh san xuat.', '<p>Phu hop cac du an khu cong nghiep can tien do nhanh va bao cao ro rang.</p>', 'factory', 'seed/media/service-drilling-rig.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 64 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-hinh'), 'Do dac ban do dia hinh bang drone', 'do-dac-ban-do-dia-hinh-bang-drone', 'Bay chup, xu ly du lieu va thanh lap ban do dia hinh so.', '<p>Dich vu phuc vu quy hoach, giao thong, khu do thi va cong trinh cong nghiep.</p>', 'map', 'seed/media/service-topography-drone.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 58 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-hinh'), 'Cam moc va luoi khong che thi cong', 'cam-moc-va-luoi-khong-che-thi-cong', 'Lap luoi toa do, cao do va moc dinh vi thi cong.', '<p>Dam bao so lieu chinh xac va dong bo trong suot qua trinh thi cong.</p>', 'pin', 'seed/media/service-topography-drone.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 52 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-thuy-van'), 'Khao sat muc nuoc ngam va dia chat thuy van', 'khao-sat-muc-nuoc-ngam-va-dia-chat-thuy-van', 'Quan trac muc nuoc, danh gia dong chay va dac diem tang chua nuoc.', '<p>Du lieu giup tinh toan ha muc nuoc, chong tham va lua chon giai phap thi cong.</p>', 'water', 'seed/media/service-lab-testing.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 46 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'thi-nghiem-chuyen-nganh-xay-dung'), 'Thi nghiem co ly dat da trong phong', 'thi-nghiem-co-ly-dat-da-trong-phong', 'Thuc hien cac chi tieu co ly va suc chiu tai cua mau dat da.', '<p>He thong phong thi nghiem phuc vu nhieu chi tieu tu co ban den chuyen sau.</p>', 'flask', 'seed/media/service-lab-testing.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 39 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'thi-nghiem-chuyen-nganh-xay-dung'), 'Thi nghiem hien truong SPT va CPTu', 'thi-nghiem-hien-truong-spt-va-cptu', 'Ket hop cac phuong phap de danh gia suc khang va dia tang tai cho.', '<p>Goi dich vu phu hop cac du an can du lieu lien tuc va do tin cay cao.</p>', 'gauge', 'seed/media/service-lab-testing.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 34 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'quan-trac-cong-trinh'), 'Quan trac lun nghieng cong trinh', 'quan-trac-lun-nghieng-cong-trinh', 'Theo doi bien dang cong trinh trong qua trinh thi cong va van hanh.', '<p>He thong bao cao dinh ky va canh bao som cac bien dong bat thuong.</p>', 'radar', 'seed/media/project-highway.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 28 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'tu-van-giam-sat-khao-sat'), 'Tu van giam sat cong tac khao sat', 'tu-van-giam-sat-cong-tac-khao-sat', 'Giam sat chat luong khoi luong va quy trinh khao sat.', '<p>Dam bao ho so khao sat dat yeu cau phap ly va ky thuat cho buoc thiet ke.</p>', 'shield', 'seed/media/project-factory.jpg', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 22 DAY)),
    ((SELECT id FROM service_categories WHERE slug = 'xay-lap'), 'Thi cong xu ly nen dat yeu', 'thi-cong-xu-ly-nen-dat-yeu', 'Ho tro thi cong cac giai phap gia co va xu ly nen.', '<p>Du lieu nhap de kiem tra danh sach dich vu ban nhap tren trang quan tri.</p>', 'build', 'seed/media/project-housing.jpg', 'DRAFT', NULL);

INSERT INTO projects (category_id, title, slug, client_name, location, started_at, completed_at, scale_text, cover_image_path, gallery_json, content, status, published_at)
VALUES
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Khao sat dia chat tuyen duong ven do', 'khao-sat-dia-chat-tuyen-duong-ven-do', 'Ban QLDA Ha tang Ha Noi', 'Ha Noi', DATE_SUB(NOW(), INTERVAL 220 DAY), DATE_SUB(NOW(), INTERVAL 180 DAY), '32 ho khoan, 1.250 m khoan', 'seed/media/project-highway.jpg', '["seed/media/project-highway.jpg","seed/media/service-drilling-rig.jpg"]', '<p>Du an phuc vu lap thiet ke ky thuat cho tuyen duong ket noi khu do thi moi.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 175 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Khao sat nha may che tao co khi', 'khao-sat-nha-may-che-tao-co-khi', 'Hung Thinh Industrial', 'Hung Yen', DATE_SUB(NOW(), INTERVAL 210 DAY), DATE_SUB(NOW(), INTERVAL 165 DAY), '18 ho khoan, 760 m khoan', 'seed/media/project-factory.jpg', '["seed/media/project-factory.jpg","seed/media/service-lab-testing.jpg"]', '<p>Thuc hien khoan, SPT va thi nghiem co ly de de xuat giai phap mong coc.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 160 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Khao sat khu nha o thuong mai', 'khao-sat-khu-nha-o-thuong-mai', 'Minh Long Land', 'Bac Ninh', DATE_SUB(NOW(), INTERVAL 198 DAY), DATE_SUB(NOW(), INTERVAL 152 DAY), '24 ho khoan, 980 m khoan', 'seed/media/project-housing.jpg', '["seed/media/project-housing.jpg","seed/media/service-drilling-rig.jpg"]', '<p>Ho so tap trung phan tich dia tang dat yeu va giai phap xu ly nen cuc bo.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 148 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-hinh'), 'Do dac dia hinh khu do thi sinh thai', 'do-dac-dia-hinh-khu-do-thi-sinh-thai', 'Green Valley', 'Vinh Phuc', DATE_SUB(NOW(), INTERVAL 170 DAY), DATE_SUB(NOW(), INTERVAL 145 DAY), '65 ha do ve chi tiet', 'seed/media/service-topography-drone.jpg', '["seed/media/service-topography-drone.jpg"]', '<p>Bay chup drone ket hop GPS RTK va toan dac dien tu.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 140 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-hinh'), 'Thanh lap ban do hien trang nha may dien', 'thanh-lap-ban-do-hien-trang-nha-may-dien', 'Power Build', 'Hai Phong', DATE_SUB(NOW(), INTERVAL 162 DAY), DATE_SUB(NOW(), INTERVAL 133 DAY), '22 ha hien trang', 'seed/media/service-topography-drone.jpg', '["seed/media/service-topography-drone.jpg","seed/media/project-factory.jpg"]', '<p>Du lieu dau vao phuc vu mo rong nha may va bo tri ha tang ky thuat.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 128 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-chat-thuy-van'), 'Quan trac muc nuoc ngam du an ham ngam', 'quan-trac-muc-nuoc-ngam-du-an-ham-ngam', 'Metro Civil', 'Ha Noi', DATE_SUB(NOW(), INTERVAL 150 DAY), DATE_SUB(NOW(), INTERVAL 112 DAY), '8 gieng quan trac, 90 ngay do', 'seed/media/project-highway.jpg', '["seed/media/project-highway.jpg","seed/media/project-housing.jpg"]', '<p>Ket qua giup danh gia anh huong ha muc nuoc trong qua trinh dao ho mong sau.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 108 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'thi-nghiem-cong-trinh'), 'Thi nghiem nen mong khu nha xưởng logistics', 'thi-nghiem-nen-mong-khu-nha-xuong-logistics', 'North Hub', 'Hai Duong', DATE_SUB(NOW(), INTERVAL 138 DAY), DATE_SUB(NOW(), INTERVAL 102 DAY), '215 mau thi nghiem', 'seed/media/service-lab-testing.jpg', '["seed/media/service-lab-testing.jpg"]', '<p>Thi nghiem trong phong va hien truong de danh gia kha nang xu ly nen cho khu logistic.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 98 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'thi-nghiem-cong-trinh'), 'Kiem dinh chat luong vat lieu du an cau vuot', 'kiem-dinh-chat-luong-vat-lieu-du-an-cau-vuot', 'Urban Infra', 'Ha Nam', DATE_SUB(NOW(), INTERVAL 124 DAY), DATE_SUB(NOW(), INTERVAL 95 DAY), '320 chi tieu vat lieu', 'seed/media/service-lab-testing.jpg', '["seed/media/service-lab-testing.jpg","seed/media/project-highway.jpg"]', '<p>Ho so thu nghiem phuc vu nghiem thu cac dot thi cong ket cau chinh.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 90 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Khao sat trung tam du lieu', 'khao-sat-trung-tam-du-lieu', 'Viet Data Hub', 'Hoa Lac', DATE_SUB(NOW(), INTERVAL 110 DAY), DATE_SUB(NOW(), INTERVAL 78 DAY), '20 ho khoan, 840 m khoan', 'seed/media/project-factory.jpg', '["seed/media/project-factory.jpg"]', '<p>Du an can kiem soat bien dang va danh gia kha nang thi cong tren nen dat yeu.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 72 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-hinh'), 'Do dac bo sung hanh lang duong day', 'do-dac-bo-sung-hanh-lang-duong-day', 'National Grid Support', 'Thai Nguyen', DATE_SUB(NOW(), INTERVAL 95 DAY), DATE_SUB(NOW(), INTERVAL 70 DAY), '14 km tuyen do', 'seed/media/service-topography-drone.jpg', '["seed/media/service-topography-drone.jpg","seed/media/equipment-gps-01.jpg"]', '<p>Do dac bo sung phuc vu dieu chinh huong tuyen va vi tri cot.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 64 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'khao-sat-dia-chat-thuy-van'), 'Danh gia dia chat thuy van khu cong nghiep moi', 'danh-gia-dia-chat-thuy-van-khu-cong-nghiep-moi', 'East Gate IP', 'Quang Ninh', DATE_SUB(NOW(), INTERVAL 88 DAY), DATE_SUB(NOW(), INTERVAL 56 DAY), '6 lo khoan, 4 gieng quan trac', 'seed/media/project-housing.jpg', '["seed/media/project-housing.jpg","seed/media/service-lab-testing.jpg"]', '<p>Danh gia dieu kien thuy van va de xuat phuong an thoat nuoc, ha muc nuoc ngam.</p>', 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 52 DAY)),
    ((SELECT id FROM project_categories WHERE slug = 'thi-nghiem-cong-trinh'), 'Thi nghiem vat lieu khu nghi duong ven bien', 'thi-nghiem-vat-lieu-khu-nghi-duong-ven-bien', 'Blue Coast Resort', 'Hai Phong', DATE_SUB(NOW(), INTERVAL 62 DAY), NULL, 'Dang trien khai 140 mau', 'seed/media/service-lab-testing.jpg', '["seed/media/service-lab-testing.jpg","seed/media/project-housing.jpg"]', '<p>Ban nhap du lieu de kiem tra trang thai dang trien khai tren he thong.</p>', 'DRAFT', NULL);

INSERT INTO equipments (name, slug, model, manufacturer, production_year, description, cover_image_path, status, sort_order)
VALUES
    ('May khoan XY-1', 'may-khoan-xy-1', 'XY-1', 'Jiangsu Geotech', 2019, 'May khoan phuc vu khoan dia chat cong trinh quy mo vua.', 'seed/media/equipment-drill-01.jpg', 'PUBLISHED', 1),
    ('May khoan XY-4', 'may-khoan-xy-4', 'XY-4', 'Jiangsu Geotech', 2021, 'May khoan cong suat lon cho cong trinh can chieu sau khoan lon.', 'seed/media/equipment-drill-01.jpg', 'PUBLISHED', 2),
    ('Bo thiet bi SPT tu dong', 'bo-thiet-bi-spt-tu-dong', 'SPT Auto', 'GeoTest', 2020, 'He thong dong xuyen tieu chuan ghi nhan du lieu nhanh.', 'seed/media/equipment-cpt-01.jpg', 'PUBLISHED', 3),
    ('He thong CPTu 20T', 'he-thong-cptu-20t', 'CPTu-20T', 'APAFOR', 2022, 'Thiet bi xuyen tinh khet do lien tuc suc khang mui va ap luc nuoc lo rong.', 'seed/media/equipment-cpt-01.jpg', 'PUBLISHED', 4),
    ('May toan dac dien tu Leica TS07', 'may-toan-dac-dien-tu-leica-ts07', 'TS07', 'Leica', 2021, 'May toan dac do ve, bo tri va theo doi bien dang.', 'seed/media/equipment-gps-01.jpg', 'PUBLISHED', 5),
    ('May GPS RTK Rover', 'may-gps-rtk-rover', 'V200', 'Hi-Target', 2023, 'Thiet bi GPS do dac dia hinh va khong che thi cong.', 'seed/media/equipment-gps-01.jpg', 'PUBLISHED', 6),
    ('Thiet bi bay drone do ve', 'thiet-bi-bay-drone-do-ve', 'Mavic 3E', 'DJI', 2023, 'Drone chup anh phuc vu thanh lap ban do dia hinh.', 'seed/media/equipment-gps-01.jpg', 'PUBLISHED', 7),
    ('May nen 3 truc', 'may-nen-3-truc', 'TSZ-6A', 'SoilLab', 2018, 'Thiet bi thi nghiem nen 3 truc cho mau dat.', 'seed/media/equipment-lab-01.jpg', 'PUBLISHED', 8),
    ('May cat canh nhanh', 'may-cat-canh-nhanh', 'DSJ-2', 'SoilLab', 2019, 'Thiet bi cat canh xac dinh suc chong cat cua dat.', 'seed/media/equipment-lab-01.jpg', 'PUBLISHED', 9),
    ('May xac dinh gioi han Atterberg', 'may-xac-dinh-gioi-han-atterberg', 'Atterberg Pro', 'GeoLab', 2020, 'Bo thiet bi xac dinh do deo va do chay cua dat min.', 'seed/media/equipment-lab-01.jpg', 'PUBLISHED', 10),
    ('May do muc nuoc ngam', 'may-do-muc-nuoc-ngam', 'WaterLine 100', 'HydroTech', 2021, 'Thiet bi do muc nuoc ngam va quan trac theo giai doan.', 'seed/media/equipment-cpt-01.jpg', 'PUBLISHED', 11),
    ('Cam bien quan trac lun', 'cam-bien-quan-trac-lun', 'Settlement Pro', 'MonitorX', 2022, 'Cam bien va bo ghi phuc vu quan trac lun tu dong.', 'seed/media/equipment-cpt-01.jpg', 'PUBLISHED', 12),
    ('May khoan phu tro HXY-8', 'may-khoan-phu-tro-hxy-8', 'HXY-8', 'Huabei', 2017, 'May khoan du phong cho cac cong trinh can tang ca thi cong.', 'seed/media/equipment-drill-01.jpg', 'DRAFT', 13),
    ('May thu nghiem CBR', 'may-thu-nghiem-cbr', 'CBR-50', 'RoadLab', 2020, 'Thiet bi thu nghiem CBR cho nen duong va vat lieu dap.', 'seed/media/equipment-lab-01.jpg', 'DRAFT', 14),
    ('He thong quan trac nghieng', 'he-thong-quan-trac-nghieng', 'Tilt Watch', 'MonitorX', 2024, 'Thiet bi quan trac nghieng cho ho mong va cong trinh lan can.', 'seed/media/equipment-cpt-01.jpg', 'DRAFT', 15);

INSERT INTO contacts (full_name, company_name, phone, email, subject, message, status)
VALUES
    ('Nguyen Van An', 'An Phat Invest', '0901000001', 'an.nguyen@example.com', 'Tu van khao sat cho nha xuong', 'Can bao gia khao sat dia chat cho nha xuong 2 tang tai Hung Yen.', 'NEW'),
    ('Tran Thu Ha', 'Ha Thanh Design', '0901000002', 'ha.tran@example.com', 'Do dac dia hinh', 'Can lap ban do dia hinh ty le 1/500 cho khu dat 12 ha.', 'NEW'),
    ('Le Minh Duc', 'VietBuild', '0901000003', 'duc.le@example.com', 'Thi nghiem nen mong', 'Muon tham khao bang gia thi nghiem dat trong phong.', 'IN_PROGRESS'),
    ('Pham Quang Huy', 'QH Construction', '0901000004', 'huy.pham@example.com', 'Quan trac cong trinh', 'Du an can lap de xuat quan trac lun va nghieng trong 6 thang.', 'IN_PROGRESS'),
    ('Hoang Mai Lan', 'Lan Anh Holdings', '0901000005', 'lan.hoang@example.com', 'Khao sat dia chat', 'Can khao sat bo sung cho tang ham va khu de xe ngam.', 'RESOLVED'),
    ('Bui Anh Tuan', 'Tuan Minh Logistics', '0901000006', 'tuan.bui@example.com', 'Xin ho so nang luc', 'Vui long gui ho so nang luc va danh muc thiet bi hien co.', 'RESOLVED'),
    ('Do Thi Yen', 'Yen River Park', '0901000007', 'yen.do@example.com', 'Tu van thuy van', 'Can danh gia muc nuoc ngam khu ven song truoc khi thi cong.', 'NEW'),
    ('Dang Quoc Bao', 'Bao Son Energy', '0901000008', 'bao.dang@example.com', 'Do ve hien trang', 'Can do ve bo sung phuc vu dieu chinh thiet ke tram bien ap.', 'NEW'),
    ('Vu Thanh Nam', 'Nam Khanh Group', '0901000009', 'nam.vu@example.com', 'Thi nghiem vat lieu', 'Hoi ve tien do tra ket qua thi nghiem be tong va thep.', 'IN_PROGRESS'),
    ('Nguyen Bich Ngoc', 'NBN Homes', '0901000010', 'ngoc.nguyen@example.com', 'Khach hang tiem nang', 'Can don vi khao sat cho du an nha o lien ke sap trien khai.', 'NEW'),
    ('Pham Duc Long', 'Long Minh Infra', '0901000011', 'long.pham@example.com', 'Moi hop trao doi', 'Muon sap xep lich hop online de trao doi pham vi cong viec.', 'RESOLVED'),
    ('Trinh Gia Bao', 'Gia Bao Tech', '0901000012', 'bao.trinh@example.com', 'Bao gia nhanh', 'Can bao gia nhanh cho khao sat nha may dien tu trong tuan nay.', 'NEW');

INSERT INTO quote_requests (full_name, company_name, phone, email, service_category_id, project_location, request_detail, status)
VALUES
    ('Nguyen Manh Cuong', 'Cuong Phat Corp', '0912000001', 'cuong.nguyen@example.com', (SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Gia Lam, Ha Noi', 'Can bao gia khao sat 15 ho khoan cho du an nha xuong cong nghiep.', 'NEW'),
    ('Tran Kim Oanh', 'Oanh Duong Land', '0912000002', 'oanh.tran@example.com', (SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-hinh'), 'Me Linh, Ha Noi', 'Can do dac ban do dia hinh khu dat 18 ha trong 10 ngay.', 'NEW'),
    ('Le Anh Tuan', 'Tuan Anh Build', '0912000003', 'tuan.le@example.com', (SELECT id FROM service_categories WHERE slug = 'thi-nghiem-chuyen-nganh-xay-dung'), 'Bac Giang', 'Can thi nghiem co ly cho 120 mau dat va 40 mau da.', 'IN_PROGRESS'),
    ('Pham Thu Trang', 'Trang Minh Urban', '0912000004', 'trang.pham@example.com', (SELECT id FROM service_categories WHERE slug = 'quan-trac-cong-trinh'), 'Ha Dong, Ha Noi', 'Can de xuat phuong an quan trac cho ho mong sau gan nha dan.', 'NEW'),
    ('Do Xuan Bach', 'Bach Viet Industry', '0912000005', 'bach.do@example.com', (SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-thuy-van'), 'Quang Ninh', 'Can danh gia dia chat thuy van cho khu cong nghiep moi.', 'IN_PROGRESS'),
    ('Hoang Ngoc Anh', 'Ngoc Anh Resort', '0912000006', 'anh.hoang@example.com', (SELECT id FROM service_categories WHERE slug = 'tu-van-giam-sat-khao-sat'), 'Cat Ba, Hai Phong', 'Can tu van giam sat cong tac khao sat do don vi khac thuc hien.', 'RESOLVED'),
    ('Vu Tien Dat', 'Dat Thanh Infra', '0912000007', 'dat.vu@example.com', (SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Ha Nam', 'Can bo sung 8 ho khoan cho du an cau vuot.', 'NEW'),
    ('Nguyen Thu Huong', 'Huong Giang Trading', '0912000008', 'huong.nguyen@example.com', (SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-hinh'), 'Thai Nguyen', 'Can cam moc va lap luoi khong che cho cong trinh ha tang.', 'RESOLVED'),
    ('Dang Van Son', 'Son River Energy', '0912000009', 'son.dang@example.com', (SELECT id FROM service_categories WHERE slug = 'thi-nghiem-chuyen-nganh-xay-dung'), 'Hoa Binh', 'Can thu nghiem vat lieu dap va CBR cho tuyen duong cong vu.', 'NEW'),
    ('Bui Thi Hoa', 'Hoa Binh Home', '0912000010', 'hoa.bui@example.com', (SELECT id FROM service_categories WHERE slug = 'xay-lap'), 'Bac Ninh', 'Can trao doi giai phap xu ly nen dat yeu cho khu nha o.', 'IN_PROGRESS'),
    ('Tran Van Minh', 'Minh Quang EPC', '0912000011', 'minh.tran@example.com', (SELECT id FROM service_categories WHERE slug = 'quan-trac-cong-trinh'), 'Hai Duong', 'Can he thong quan trac lun trong 9 thang thi cong.', 'RESOLVED'),
    ('Phan Hai Yen', 'Hai Yen Center', '0912000012', 'yen.phan@example.com', (SELECT id FROM service_categories WHERE slug = 'khao-sat-dia-chat-cong-trinh'), 'Dong Anh, Ha Noi', 'Can bao gia tron goi khao sat va lap bao cao dia chat cong trinh.', 'NEW');

INSERT INTO menu_items (menu_id, parent_id, title, item_type, ref_id, url, icon, sort_order, is_visible)
VALUES
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Trang chu', 'URL', NULL, '/', 'home', 1, b'1'),
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Gioi thieu', 'PAGE', (SELECT id FROM pages WHERE slug = 'gioi-thieu-cong-ty'), '/gioi-thieu-cong-ty', 'info', 2, b'1'),
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Dich vu', 'URL', NULL, '/dich-vu', 'briefcase', 3, b'1'),
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Du an', 'URL', NULL, '/du-an', 'folder', 4, b'1'),
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Thiet bi', 'URL', NULL, '/thiet-bi', 'tool', 5, b'1'),
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Tin tuc', 'POST_CATEGORY', (SELECT id FROM post_categories WHERE slug = 'tin-tuc'), '/tin-tuc', 'newspaper', 6, b'1'),
    ((SELECT id FROM menus WHERE code = 'HEADER_MAIN'), NULL, 'Lien he', 'URL', NULL, '/lien-he', 'phone', 7, b'1'),
    ((SELECT id FROM menus WHERE code = 'FOOTER_MAIN'), NULL, 'Chinh sach bao mat', 'PAGE', (SELECT id FROM pages WHERE slug = 'chinh-sach-bao-mat'), '/chinh-sach-bao-mat', 'shield', 1, b'1'),
    ((SELECT id FROM menus WHERE code = 'FOOTER_MAIN'), NULL, 'Dieu khoan su dung', 'PAGE', (SELECT id FROM pages WHERE slug = 'dieu-khoan-su-dung'), '/dieu-khoan-su-dung', 'file', 2, b'1'),
    ((SELECT id FROM menus WHERE code = 'FOOTER_MAIN'), NULL, 'Nang luc thiet bi', 'PAGE', (SELECT id FROM pages WHERE slug = 'nang-luc-thiet-bi'), '/nang-luc-thiet-bi', 'tool', 3, b'1');
